# Generated by Django 5.0.2 on 2024-02-13 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                ("car_id", models.IntegerField(primary_key=True, serialize=False)),
                ("car_current_location", models.CharField(max_length=50)),
                ("car_brand", models.CharField(max_length=20)),
                ("car_model", models.CharField(max_length=50)),
                ("car_price_perday", models.FloatField()),
                ("car_pick_up_date", models.DateField(null=True)),
                ("car_pick_up_time", models.TimeField(null=True)),
                ("car_drop_off_date", models.DateField(null=True)),
                ("car_drop_off_time", models.TimeField(null=True)),
                ("car_description", models.TextField()),
                ("car_img", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.IntegerField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=100)),
                ("customer_email", models.EmailField(max_length=254)),
                ("customer_phone", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("booking_id", models.IntegerField(primary_key=True, serialize=False)),
                ("car_drop_off_location", models.CharField(max_length=50)),
                ("booking_date", models.DateTimeField()),
                (
                    "car_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="car_reservation.car",
                    ),
                ),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="car_reservation.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("invoice_id", models.IntegerField(primary_key=True, serialize=False)),
                ("amount", models.FloatField()),
                ("created_on", models.DateTimeField()),
                (
                    "booking_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="car_reservation.booking",
                    ),
                ),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="car_reservation.customer",
                    ),
                ),
            ],
        ),
    ]
