# Generated by Django 5.0.2 on 2024-02-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_reservation", "0002_alter_car_car_drop_off_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="car_description",
        ),
        migrations.AddField(
            model_name="car",
            name="Co2_fuel_Diesel",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="Cylinders",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="Drvie",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="Fuel_Type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="Transmission",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="Vehicle_Size_Class",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="Year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="baseModel",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="city_Mpg_For_Diesel",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="car_price_perday",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
