# Generated by Django 5.0.2 on 2024-02-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "car_reservation",
            "0003_remove_car_car_description_car_co2_fuel_diesel_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_price_perday",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
