# Generated by Django 5.0.2 on 2024-02-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_reservation", "0004_alter_car_car_price_perday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="Cylinders",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="car_img",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="car",
            name="city_Mpg_For_Diesel",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
