# Generated by Django 5.0.2 on 2024-02-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_reservation", "0005_alter_car_cylinders_alter_car_car_img_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="availablality",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
