# Generated by Django 5.0.2 on 2024-02-17 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_reservation", "0006_car_availablality"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="availablality",
            new_name="availability",
        ),
    ]
