# Generated by Django 5.0.2 on 2024-02-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_reservation", "0008_alter_car_car_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_img",
            field=models.ImageField(upload_to=""),
        ),
    ]
