# Generated by Django 5.0.2 on 2024-02-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_reservation", "0009_alter_car_car_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
