# Generated by Django 5.0.2 on 2024-02-18 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_reservation", "0010_alter_booking_booking_date_alter_invoice_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="car_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="car_reservation.car"
            ),
        ),
    ]
