# Generated by Django 5.0.2 on 2024-02-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_reservation", "0011_alter_booking_car_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_img",
            field=models.FilePathField(),
        ),
    ]
