# Generated by Django 5.0.2 on 2024-02-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_reservation", "0019_alter_car_car_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_img",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
