# Generated by Django 5.0.2 on 2024-02-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_reservation", "0020_alter_car_car_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_price_perday",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
