# Generated by Django 5.0.2 on 2024-02-28 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_reservation", "0021_alter_car_car_price_perday"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="car_drop_off_location",
        ),
    ]
