# Generated by Django 5.0.2 on 2024-03-08 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_reservation", "0023_remove_booking_customer_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="car_id",
            new_name="car",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="booking_id",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="invoice_id",
        ),
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="id",
            field=models.AutoField(
                default="0000000", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.BigAutoField(
                default="000000", primary_key=True, serialize=False
            ),
        ),
    ]
