# Generated by Django 5.0.2 on 2024-03-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "car_reservation",
            "0024_rename_car_id_booking_car_remove_booking_booking_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="car",
            new_name="car_id",
        ),
        migrations.AlterField(
            model_name="booking",
            name="id",
            field=models.AutoField(default="0", primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.BigAutoField(default="0", primary_key=True, serialize=False),
        ),
    ]
