# Generated by Django 5.0.2 on 2024-03-08 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_reservation", "0026_rename_booking_id_invoice_booking"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="id",
            new_name="invoice_id",
        ),
    ]
