# Generated by Django 5.0.2 on 2024-03-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_reservation", "0028_alter_booking_id_alter_invoice_invoice_id"),
    ]

    operations = []
