# Generated by Django 5.0.2 on 2024-03-08 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_reservation", "0029_auto_20240308_1502"),
    ]

    operations = []
