# Generated by Django 5.0.2 on 2024-03-08 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_reservation", "0030_auto_20240308_1503"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="booking",
            new_name="id",
        ),
    ]
