# Generated by Django 5.0.2 on 2024-03-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_reservation", "0035_rename_id_booking_booking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="user",
        ),
    ]
