# Generated by Django 5.0.2 on 2024-03-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_reservation", "0036_remove_invoice_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="booking",
            new_name="booking_id",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="booking",
            new_name="booking_id",
        ),
    ]
