# Generated by Django 5.0.2 on 2024-03-08 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_reservation", "0038_rename_user_booking_user_id_invoice_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="Drvie",
            new_name="Drive",
        ),
    ]
