# Generated by Django 5.0.2 on 2024-03-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_reservation", "0039_rename_drvie_car_drive"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="booked",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
