# Generated by Django 5.0.2 on 2024-03-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_reservation", "0040_car_booked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="booked",
            field=models.BooleanField(default=False),
        ),
    ]
