# Generated by Django 5.0.2 on 2024-03-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_reservation", "0041_alter_car_booked"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="pending",
            field=models.BooleanField(default=False),
        ),
    ]
