# Generated by Django 5.0.2 on 2024-03-11 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_reservation", "0043_remove_invoice_created_on"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="booking_id",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="user_id",
        ),
        migrations.CreateModel(
            name="Carbooking",
            fields=[
                ("booking_id", models.AutoField(primary_key=True, serialize=False)),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                ("amount", models.FloatField()),
                ("pick_up_date", models.DateField(blank=True, null=True)),
                ("pick_up_time", models.TimeField(blank=True, null=True)),
                ("drop_off_date", models.DateField(blank=True, null=True)),
                ("drop_off_time", models.TimeField(blank=True, null=True)),
                (
                    "car_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="car_reservation.car",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Booking",
        ),
        migrations.DeleteModel(
            name="Invoice",
        ),
    ]
