# Generated by Django 5.0.2 on 2024-03-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "car_reservation",
            "0044_remove_invoice_booking_id_remove_invoice_user_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="carbooking",
            name="canceled",
            field=models.BooleanField(default=False),
        ),
    ]
