# Generated by Django 5.0.2 on 2024-03-27 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("activity_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, null=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(null=True)),
                ("pricea", models.FloatField(max_length=10)),
                ("category", models.CharField(max_length=20, null=True)),
                ("city", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Activitybooking",
            fields=[
                ("booking_id", models.AutoField(primary_key=True, serialize=False)),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                ("canceled", models.BooleanField(default=False)),
                ("tickets_nb", models.IntegerField()),
                (
                    "activity_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="attractions.activity",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tickets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("nba", models.IntegerField()),
                (
                    "activity_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="attractions.activity",
                    ),
                ),
            ],
        ),
    ]
