# Generated by Django 5.0.2 on 2024-03-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attractions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="name",
        ),
    ]
