# Generated by Django 5.0.4 on 2024-04-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0030_booking_checked_in_tracker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
