# Generated by Django 5.0.4 on 2024-04-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0031_hotel_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='country_code',
        ),
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
